### ISSUE TITLE
Serve updated static files does not work in our dev environment (nginx)

### ISSUE THREAD

**Issue by felixble** [sqe-galerie/bildergalerie#12]
If you change any project file vagrant should sync the changes between host and guest systems and after a browser reload the changes should be applied in our application. Unfortunately, this does not work for static files.

Steps to reproduce:
* Start vagrant with `vagrant up`
* verify that the application is running and request a static file (e.g open http://5.5.5.5/resources/js/picture_uploader.js in your browser)
* open the requested static file in your IDE and change it (e.g. add a comment in the first line)
* verify that the synced file exists in the synced folder of the guest system (`vagrant ssh` and navigate to `/vagrant_data/`. There you can locate the file.
* reload the browser --> nothing changed!

**Comment by felixble** [comment]
It seems to be a problem with the nginx config on our vagrant environment. Turning off the nginx `sendfile`-feature solves the problem: https://jeremyfelt.com/2013/01/08/clear-nginx-cache-in-vagrant/

I will adjust the vagrant bootstrap script to change the config after a new vagrant box will be started. So `vagrant halt && vagrant destroy && vagrant up` should solve the problem.

**Comment by dobecker1** [comment]
closed with #13
