### ISSUE TITLE
Setup sonarqube for static code analysis

### ISSUE THREAD

**Issue by felixble** [sqe-galerie/bildergalerie#17]

**Comment by jasteuer** [comment]
https://sonarcloud.io/organizations/de-htwsaar-sqe-bildergalerie/projects
 
# Useful Links:
https://about.sonarcloud.io/get-started/
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner

# How to run analysis manual
- see the guide
- setup sonar-scanner and configure it (`.../sonar-scanner-XXX/conf/sonar-scanner.properties`), eg set `sonar.login` to your auth token
- run analysis with the command `sonar-scanner`

# TODO
- setup Travis CI to run sonar-scanner #16 
- make sure, that every team member can run analysis and has permissions to send the results to sonarcloud

**Comment by felixble** [comment]
@jasteuer Could you please convert the remaining todos into issues? Otherwise we might forget about it.
