### ISSUE TITLE
Screenshot when e2e test fails on travis

### ISSUE THREAD

**Issue by felixble** [sqe-galerie/bildergalerie#30]
Sometimes it is very hard to debug failing e2e tests on travis ci. It would be very helpful if a screenshot would be taken if a test failed. Then the screenshots should be uploaded somewhere so we can access them.

Maybe this helps: https://medium.com/@dikareva1209/all-the-tricks-that-help-you-debug-testcafe-tests-af0418220d

**Comment by felixble** [comment]
I configured travis to run out e2e tests on chrome only, temporarily. Could you please switch back and configure travis to run the tests on all browsers. With the screenshots we can then inspect and debug the tests way better, I hope.

The current problem occurs when deleting an exhibition on browser chromium on travis. I installed chromium on mac which worked perfectly. My first thought was that the default conformation dialog causes the issues. Surprisingly, I could not see whether the dialog opens or not when watching the tests run locally.

**Comment by jasteuer** [comment]
More Infos:
https://github.com/sqe-galerie/bildergalerie/wiki/Developer-Infos
