### ISSUE TITLE
Combine all spread config parameters into one file

### ISSUE THREAD

**Issue by felixble** [sqe-galerie/bildergalerie#34]
It turned out that we have multiple configuration files for different purposes containing almost the same data (e.g. database connection). If a different configuration is needed multiple files have to be updated accordingly. Even if we use the same development environment (vagrant) we have at least two different environments because the CI build server (travis ci) cannot use vagrant to run the build.

### Which config files exists and what is their purpose?
* `local.php` contains parameters for the main application which may differ on different environments (e.g. database connection, e-mail addresses, ...) -- is not included in the vcs
* `config.php` includes the `local.php` and is part of the vcs
* `test/e2e/config.js` contains the server url to access the web application
* `test/utils/dbConfig.json` contains the database connection parameters necessary for our test utils (e.g. rest database node script)

### From where do we have to access the configurations
* php application code
* javascript code for utils and e2e tests
* shell scripts for setting up travis ci or vagrant development environemnt

#### Provide a single json file for all parameters
* Could be access from javascript easily
* Should be possible to access from `config.php` which then could set the php constancs
* Is it possible to parse json in a shell script ?!

#### Provide a `.env` file containing key value pairs
* PHP lib [dotenv](https://github.com/vlucas/phpdotenv) can parse such a file
* Could be loaded as environment variables before executing shell scripts or node scripts
* Not sure if this will work on windows (this is currently necessary to run testcafe) ?!

## Decision
We use the second approach: `.env` containing key value pairs

### Affected places
- [x] `local.php` / `config.php` covers configuration for the application
- [x] `test/e2e/config.js` covers configuration for our e2e tests
- [x] Config for our node.js test utils tools
- [x] `travis-setup-db.sh` needs database configuration parameters
- [x] `vagrant/bootstrap.sh` and `vagrant/after-up.sh` needs database configuration parameters
- [x] `vagrant/bootstrap.sh` should create `.env` file with default vagrant settings (if file not available)
- [x] `.travis.yml` should overwrite `.env` file with custom settings used for travis
- [x] Explain usage of `.env` in the projects main `README`

**Comment by jasteuer** [comment]
I think second solution (.env file) would be the best:
- we does not depend on windows (developer use linux via vagrant, travis use linux)
- supported in some way by all config accessors

**Comment by felixble** [comment]
@jasteuer Unfortunately, right now we still depend on windows since the end2end tests run on the hosts and not on the vagrant vm. However, we could use [env-cmd](https://github.com/toddbluhm/env-cmd) which is a node cli tool to read a config file and provide the settings as environment variables. Maybe this will work on windows, too.

**Comment by jasteuer** [comment]
@felixble Yes, you are right. I think we should work on this issue, after or during #33

**Comment by frederic-welsch** [comment]
FYI: #28 sets a filesize parameter. Please add this value to the config. Thanks 👍

**Comment by felixble** [comment]
@frederic-welsch not so easy. We (primary) do not use the vagrant setup for deployment (common scenario is a linux server with nginx as a webserver). When the webserver is independent from our application we cannot control its settings.
