### ISSUE TITLE
Define our "Definition of Done"

### ISSUE THREAD

**Issue by felixble** [sqe-galerie/bildergalerie#39]
To make better estimations and have an equal understanding when a taks is done we need to define exactly what steps have been made until the task is done.

Have a look at [this article](https://dzone.com/articles/definitions-done-practice) for example to see how one could write a definition of done.

The Definition of Done should available in our project wiki.

**Comment by frederic-welsch** [comment]
The Definition of Done could be found in our [wiki](https://github.com/sqe-galerie/bildergalerie/wiki/Definition-of-Done)
