### ISSUE TITLE
Sample integration test to cover repository implementations

### ISSUE THREAD

**Issue by jasteuer** [sqe-galerie/bildergalerie#58]
Todo:
- [x] Create abstract base class for our Db-Test cases where we can place all the bootstrap code
- [x] Pass database configuration as parameters to allow different configurations
- [x] Check how the coverage of the unit and the dbunit tests can be aggregated
- [x] Make sure travis executes the dbunit tests, too
- [x] Provide npm script to execute the dbunit tests
- [x] Cover ExhibitionRepo-Impl with dbunit tests

**Comment by felixble** [comment]
We can use [`phpunit/dbunit`](https://phpunit.de/manual/current/en/database.html) for this which automatically truncates the concerned tables for us and allows to insert fixtures from simple xml files.

**Comment by felixble** [comment]
To get information about the code coverage we can generate a second coverage/tests xml file. To send the complete information to sonar we then have to merge both coverage files. Maybe the tool [phpcov](https://github.com/sebastianbergmann/phpcov) can do this for us. Maybe [this](https://github.com/sebastianbergmann/phpunit/pull/685)  could be useful, too.
