### ISSUE TITLE
Set up package.json

### ISSUE THREAD

**Issue by jasteuer** [sqe-galerie/bildergalerie#9]
We need node.js for our e2e test setup (we have testcafe as dependency). Instead of installing testcafe globally define it as dev-dependency in the package json.

## ACs
- [x] Add package.json
- [x] Add testcafe as dev-dependency
- [x] Set up npm script to start our tests (and further tasks?)

**Comment by frederic-welsch** [comment]
FYI: I added a package.json in my branch according to issue #6 because of using nodejs libs such as mysql. I also added testcafe.

**Comment by felixble** [comment]
I will take care about the rest of this in #34
